name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: |
        pip install -r solodungeon/backend/requirements.txt

    - name: Run Django tests
      run: |
        cd solodungeon/backend
        python manage.py test

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node dependencies
      run: |
        cd solodungeon/frontend
        npm install

    - name: Run React tests
      run: |
        cd solodungeon/frontend
        npm test

    - name: Build React app
      run: |
        cd solodungeon/frontend
        npm run build

    - name: Lint Check
      run: |
        npm run lint

    - name: Type Check
      run: |
        npm run typecheck

    - name: Check for vulnerabilities
      run: |
        npm audit --production

    - name: Docker Build
      run: |
        docker build -t solodungeon-app -f solodungeon/Dockerfile .